---
title: "6040 Advanced statistical methods II "
author: "Lily Luk"
date: "2023-05"
output: 
  html_document: 
    highlight: pygments
    theme: flatly
---

# R notes sorted by lecture :D {.tabset}

## Overview

1. Frequentist inference, Interval estimation and Hypothesis testing [Lecture note](https://www.notion.so/1-Frequentist-Inference-Interval-Estimation-and-Hypothesis-Testing-382961a2a5ad4acaa535d95f56dde18e) | 
   [Practical](https://flatter11.github.io/6040/1.-Frequentist-Inference,-Interval-Estimation-and-Hypothesis-Testing)
    - Max likelihood
    - CI and p-value
    - `function` for user-defined functions, `optim` for max likelihood, obtain p-value of comparing groups

2. Bootstrap method [Lecture note | Practical](https://flatter11.github.io/6040/2.-Bootstrap-method)
   - Types of bootstrap, Bootstrap CI
   - `boot` package for bootstrap

3. Regression discontinuity design [Lecture note](https://flatter11.github.io/6040/3.-Regression-discontinuity-design)
   - Global approach (linear + polynomial)
   - Local approach (kernel smoothing) `np` `rdrobust`
   - Assumptions of RDD

4. Survival analysis and multiple imputation [Lecture note | Practical](https://flatter11.github.io/6040/4.-Survival-function-and-multiple-imputation)
   - Survival analysis
     - KM estimator `surv` `survfit` & log rank test  `survdiff`
     - PH model/Cox regression -- fitting model `coxph` & check assumptions `cox.zph`
     - AFT model -- fitting model `survreg`
     - Censoring & truncation analysis
   - Multiple imputation
     - Construct datasets `transcan` `aregImpute`
     - Comtine estimates `fit.mult.impute`

5. Multilevel analysis [Lecture note](https://flatter11.github.io/6040/5.-Multilevel-analysis)
   - For clustered data
   - Multilevel models formula
   - Linear mixed model (LMM)
     - random intercept model, intercept with 1 predictor model etc
     - model comparison
     - model diagnostics

6. Longitudinal analysis [Lecture note | Practical](https://flatter11.github.io/6040/6.-Longitudinal-analysis)
   - For repeated measure/longitudinal data
   - GEE model
     - Correlation structure (independence, exchangeable, ar1, unstructure)
     - Model comparison, missing data
   - GLMM model
   
7. Margianl structural model [Lecture note](https://flatter11.github.io/6040/7.-Marginal-structural-model)
   - For longitudinal data with time-dependent element
   - MSM model
     1. Estimate weight using `ipwpoint` (time-independent analysis) `ipwtm`(time-dependent)
        `ipwplot` to show distribution of weight
     2. Obtain causal effect estimate using regression model like `svyglm()`or cox model


   
Tutorial

1. Tutorial 1[Tutorial note](https://flatter11.github.io/6040/Tutorial-1)
   - After lecture 2
   - Ho chi super difficult...

2. Tutoial 2[Tutoorial note](https://flatter11.github.io/6040/Tutorial-2)
   - Multiple imputation (lecture 4)
   - Extension abt a) study missingness b) checking whether imputed data is sensible

## 1

1. Frequentist inference (proportional definition, multiple observations, log-likelihood function)
2. Interval estimation (derive CI)
3. Hypothesis testing (p-value)
-  Practical 1: 
   -  Q1 `function` for user-defined functions, `optim` for max likelihood
   -  Q2 obtain p-value of comparing groups
   -  Q3 max likelihood in complicated example

## 2

1. Type of bootstrap (non-parametric, semi-parametric, parametric)
2. Bootstrap CI
3. `boot` package

## 3

1. RDD global approach (linear + polynomial)
2. Local approach (kernel smoothing) `np` `rdrobust`
3. Checking assumptions of RDD

## 4

1. Survival analysis
   - KM estimator `surv` `survfit` & log rank test  `survdiff`
   - PH model/Cox regression -- fitting model `coxph` & check assumptions `cox.zph`
   - AFT model -- fitting model `survreg`
   - Censoring & truncation analysis
2. Multiple imputation
   - Construct datasets `transcan` `aregImpute`
   - Comtine estimates `fit.mult.impute`

## 5

1. Multilevel models formula
2. Linear mixed model (LMM)
   - random intercept model, intercept with 1 predictor model etc
   - model comparison
   - model diagnostics

## 6

1. GEE model
   - Correlation structure (independence, exchangeable, ar1, unstructure)
   - Model comparison with anova(), QIC
   - Missing data
2. GLMM model

## 7

MSM model

1. Estimate weight using `ipwpoint` (time-independent analysis) `ipwtm`(time-dependent)
   `ipwplot` to show distribution of weight
2. Obtain causal effect estimate using regression model like `svyglm()`or cox model


## T1

a. Likelihood ratio method to obtain **95%CI** (new)
b. Bootstrap R package to obtain **95%CI**
c. Obtain **MLE** for multiple samples (new)
d. Obtain **MLE** while allowing for group differnece (new)
e. Hessian and information matrix to obtain **95%CI** (new)
f. (under d) Hessian and information matrix to obtain **95%CI** while allowing for group difference; wald estimate??????? | `solve()` to compute inverse of matrix
g. (under d) Likelihood ratio for 2 estimate ???

## T2

- Lecture 4 (multiple imputation)
  - Perform multiple imputation in 3 missing datasets (MCAR, not MCAR, high missingness)
  - For each dataset, we
    1. Study missingness by visualization etc `aggr()` `marginplot()` 
       `complete.cases()` (new)
    2. Performed complete case analysis 
    3. Performed multiple imputation which includes constructing dataset, checking 
       whether imputed data is sensible (new) and combine estimate
  - The finding of this tutorial is that estimate is biased if multiple 
    imputation is not used and all variables should be used for multiple 
    imputation


